#!/bin/bash 

nextflow run main.nf -entry SPECIES_ID_WORKFLOW -profile local,singularity --fastq_dir ../../2023_1_OC_datasets/concatenated_datasets_R1_only,../../2023_1_OC_datasets/2023_4_Lexi_dried_samples,../../2023_1_OC_datasets/Additional_Fresh_Samples_rc,/home/mdstengl/for/lexi/2023_4_19_FoCo_20_21_pool,../../2023_1_OC_datasets/2021_4_7_Tillie_Fly_Pools --fastq_pattern "*_R[1]*.fastq*" -resume 
