#!/bin/bash 


nextflow run main.nf -profile local,singularity --fastq_dir ../../2023_11_OC_preprocessed_reads/trimmed_fastq_R1_only --fastq_pattern "100427*.fastq*" -resume --genome_fasta refseq/Drosophila_melanogaster.BDGP6.32.dna.toplevel.fa.gz --genome_annotation_gtf refseq/Drosophila_melanogaster.BDGP6.32.108.gtf 
