#!/bin/bash 

nextflow run main.nf -profile local,singularity --fastq_dir ../../2023_1_OC_datasets/concatenated_datasets,../../2023_1_OC_datasets/2023_4_Lexi_dried_samples,../../2023_1_OC_datasets/Additional_Fresh_Samples -resume --fastq_pattern "*_R[12]*.fastq*" --mapping_samplesheet mapping_samplesheet.txt --outdir remapping_results --skip_final_analyses
