#!/bin/bash 

# nextflow run main.nf -profile local,singularity --fastq_dir ../../2023_1_OC_datasets/concatenated_datasets_R1_only,../../2023_1_OC_datasets/2023_4_Lexi_dried_samples,../sra_datasets/fastq -resume --fastq_pattern "*_R1*.fastq*" --mapping_samplesheet mapping_samplesheet.txt 

nextflow run main.nf -profile local,singularity --fastq_dir ../../2023_11_OC_preprocessed_reads/trimmed_fastq_R1_only -resume --fastq_pattern "*.trim.fastq.gz" --mapping_samplesheet mapping_samplesheet.txt 
