#!/bin/bash 

nextflow run main.nf -profile local,singularity --fastq_dir ../../2023_1_OC_datasets/concatenated_datasets_R1_only,../../2023_1_OC_datasets/Additional_Fresh_Samples -resume --fastq_pattern "*_R1*.fastq*" --mapping_samplesheet mapping_samplesheet.txt
